export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const ROOM_JOINED = 'ROOM_JOINED'
export const TAKE_SEAT = 'take_seat'
export const SEND_MESSAGE = 'send_message'
